/*
 * This source file was generated by the Gradle 'init' task
 */
package pathgen;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Point[] startPoints;
        Point[] endPoints;
        // writeToJson(path);
    }
}
